# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secbret.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsecbret.proto\x12\nsecbret.ml\"\x8f\x01\n\x15\x43lassificationRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x12\n\nrule_score\x18\x02 \x01(\x01\x12\x1b\n\x13tier1_findings_json\x18\x03 \x01(\t\x12\x1b\n\x13tier2_findings_json\x18\x04 \x01(\t\x12\x1b\n\x13tier3_findings_json\x18\x05 \x01(\t\"U\n\x16\x43lassificationResponse\x12\x10\n\x08ml_score\x18\x01 \x01(\x01\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x15\n\rmodel_version\x18\x03 \x01(\t2]\n\x08MLScorer\x12Q\n\x08\x43lassify\x12!.secbret.ml.ClassificationRequest\x1a\".secbret.ml.ClassificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secbret_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFICATIONREQUEST']._serialized_start=30
  _globals['_CLASSIFICATIONREQUEST']._serialized_end=173
  _globals['_CLASSIFICATIONRESPONSE']._serialized_start=175
  _globals['_CLASSIFICATIONRESPONSE']._serialized_end=260
  _globals['_MLSCORER']._serialized_start=262
  _globals['_MLSCORER']._serialized_end=355
# @@protoc_insertion_point(module_scope)
